### ISSUE TITLE
dataset problem

### ISSUE THREAD

**Issue by wanghai111** [Pirazh/Vehicle_Key_Point_Orientation_Estimation#1]
Missing mean.pth.tar in the dataset

**Comment by Pirazh** [comment]
This file should be calculated based on Veri776 dataset, I will try to include it later today, for now you can use mean and standard deviation of ImageNet dataset, the results shouldn't be that different since the backbone has batchnorm layers.

**Comment by Pirazh** [comment]
The file can be found at `/data/VeRi/`
