### ISSUE TITLE
The Pretrained Model Files are corrupted in the links mentioned.

### ISSUE THREAD

**Issue by mignipunn** [Pirazh/Vehicle_Key_Point_Orientation_Estimation#12]
Hi Parazh,
I was working on this problem when I saw your work. The Pretrained Model Files are corrupted in the links mentioned. Could you please update them?

**Comment by Pirazh** [comment]
Hi, I can confirm that the provided links to the pre-trained models work properly.

**Comment by Pirazh** [comment]
Since they work properly I close this thread.
