### ISSUE TITLE
About Datasets

### ISSUE THREAD

**Issue by pswena** [Pirazh/Vehicle_Key_Point_Orientation_Estimation#13]
I want to reproduce the results in the VehicleID datasets, but I want to know how can you get the ground truth about vehicle keypoint(such as the files "keypoint_test.txt" and "keypoint_train.txt")? and "mean.pth.tar" about VehicleID datasets? Thank you!

**Comment by Pirazh** [comment]
Hi, the files "keypoint_test.txt" and "keypoint_train.txt" are obtained from [here](https://github.com/Zhongdao/VehicleReIDKeyPointData) as referenced in our documentation. You can also obtained them from `data/VehicleKeyPointData` directory. The `mean.pth.tar` file is obtained by computing mean and standard deviation for all channels across samples within the training data.
