### ISSUE TITLE
Infering the pretrained checkpoints on Compcars dataset 

### ISSUE THREAD

**Issue by techie02** [Pirazh/Vehicle_Key_Point_Orientation_Estimation#16]
Hello @Pirazh 
I am loading the pretrained checkpoints and running the model on a different car dataset (compcars). The keypoint detection does not seem very accurate. Any comments from your end will be helpful
Thank you

**Comment by Pirazh** [comment]
Hi, I believe there is a domain gap between images in VeRi and CompCars datasets and that is probably why you are seeing degradation in performance. Note that our model was only trained on the VeRi dataset. You may want to try approaches to compensate the distributional shifts.

**Comment by techie02** [comment]
Thank you for the quick response
