### ISSUE TITLE
stage1 and stage2 checkpoint seem corrupted

### ISSUE THREAD

**Issue by zhengshangdong** [Pirazh/Vehicle_Key_Point_Orientation_Estimation#2]
Hi sir，
The weights----stage1 and stage2 checkpoints seem corruped， unzipped files keep getting errors..

**Comment by Pirazh** [comment]
you should not extract the files after download as they are in the format that pytorch recognizes. Just put the files with the format *.pth.tar in the specified folders.

**Comment by zhengshangdong** [comment]
Thank you very much, sir！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Pirazh Khorramshahi"<notifications@github.com&gt;; 
发送时间: 2019年11月1日(星期五) 凌晨1:08
收件人: "Pirazh/Vehicle_Key_Point_Orientation_Estimation"<Vehicle_Key_Point_Orientation_Estimation@noreply.github.com&gt;; 
抄送: "我不管，我最丑"<1223138496@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [Pirazh/Vehicle_Key_Point_Orientation_Estimation] stage1 and stage2 checkpoint seem corrupted (#2)




you should not extract the files after download as they are in the format that pytorch recognizes. Just put the files with the format *.pth.tar in the specified folders.
