### ISSUE TITLE
Releasing adaptive heatmap selection model as well?

### ISSUE THREAD

**Issue by power0341** [Pirazh/Vehicle_Key_Point_Orientation_Estimation#4]
Thank you so much of sharing this excellent codebase, and if possible, could you also make available  the first and third part, "Global Feature Extraction" and "Adaptive Key-Point Selection and Feature Extraction" ?

**Comment by Pirazh** [comment]
Thanks for your interest in our work, however we are restricted in sharing that code. We may include a modified version of it in future and make sure to notify you.
