### ISSUE TITLE
About the ground truth

### ISSUE THREAD

**Issue by Leoshiou** [Pirazh/Vehicle_Key_Point_Orientation_Estimation#7]
Hello, I have read the "A Dual-Path Model with Adaptive Attention For Vehicle Re-Identification" paper, but I am curious, how can you get the ground truth about the vehicle keypoint (I mean the files "keypoint_test.txt" and "keypoint_train.txt")? Thank you.

**Comment by Pirazh** [comment]
Hi,  these files are included at `./data/VehicleKeyPointData/`.
