### ISSUE TITLE
about the code

### ISSUE THREAD

**Issue by xieyuhaoli** [Pirazh/Vehicle_Key_Point_Orientation_Estimation#9]
in the utilities.py file,in your test ,do you use the code : if target[n, c, 0] > 1 and target[n, c, 1] > 1:

**Comment by Pirazh** [comment]
Yes, during the testing stage, the code only considers the key-points which their ground-truth coordinates exist.

**Comment by xieyuhaoli** [comment]
> Yes, during the testing stage, the code only considers the key-points which their ground-truth coordinates exist.
In the second stage, the direction estimation has no effect on the detection of key points. In the second stage, the accuracy of the detection of key points is modified only through a section of network, right?

**Comment by Pirazh** [comment]
The refinement stage tries to yield cleaner heat-maps that outline the location of key-points. To train the refinement stage, the  weights of the course stage estimator are frozen.  In this stage, refinement of key-points and orientation estimation is done simultaneously.
